### ISSUE TITLE
Where is this xiaomi-equuleus release?

### ISSUE THREAD

**Issue by wxie2017** [althafvly/android_device_xiaomi_equuleus#2]
Hi, althafvly:

Thank you for developing LineageOS for xiaomi 8 pro - equuleus.
I have problem to download the release at
[equuleus](https://androidfilehost.com/?fid=17248734326145689170)

Is it possible for you to release it in github?

best wishes
wxie

**Comment by althafvly** [comment]
This is for twrp. Not lineageos
